INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'text',0,'','{\"text\":\"sRoland Strålberg\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'audio',2,'center','{\"src\":\"_1.mp3\",\"caption\":\"Så bra\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'youtube',1,'center','{\"track\":\"FMnVIKJJldE?si=2TFrmvMkrbqlNflB\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'youtube',4,'center','{\"track\":\"FMnVIKJJldE?si=OQCgAJIQ1MVFzvzV\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'spotify',3,'center','{\"track\":\"0QZGHIbAbWMZuoii5ypbDY\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'soundcloud',5,'center','{\"track\":\"1434718045\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'image',6,'center','{\"src\":\"2021-07-24%2012-10-05.jpeg\",\"caption\":\"dfsdafas\",\"width\":null}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'title',7,'center','{\"title\":\"asdfasdfasdf\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (0,'text',8,'left','{\"text\":\"...\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (0,'text',8,'left','{\"text\":\"...\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (0,'text',8,'left','{\"text\":\"...\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'text',9,'left','{\"text\":\"...\"}');
INSERT INTO `sections` (`articleId`,`type`,`pos`,`align`,`content`) VALUES (1,'list',8,'left','{\"style\":\"disc\",\"items\":[\"sadasdsad\"]}');
